name: Terraform Plan
on:
  push:
    branches:
      - '*'
      - '!main'
env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.TFSTATE_REGION }}
  TFSTATE_BUCKET:  ${{ secrets.TFSTATE_BUCKET }}
  TFSTATE_KEY:  ${{ vars.TFSTATE_KEY }}
  TFSTATE_REGION:  ${{ vars.TFSTATE_REGION }}
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Terraform Init
      run: |
        terraform init -backend-config="bucket=${TFSTATE_BUCKET}" -backend-config="key=${TFSTATE_KEY}" -backend-config="region=${TFSTATE_REGION}" 
    - name: Terraform validate
      run: terraform validate
    - name: Terraform Plan
      run: terraform plan